name: ForceProject
email: xxx@yyy.com
phone: +86 1234 5678
location: "#42 St, City, Country"
abstract: |-
  ForceProject是一个综合权限管理与工业监控平台，采用多层架构设计，
  集成了用户认证授权、实时传感器数据监控、有毒气体数据库管理、案例文件浏览等多种功能。

  核心特性：
  1. 完善的RBAC权限控制系统 - 支持用户、角色、权限三级管理，包含细粒度权限控制
  2. 工业传感器数据可视化 - 实时读取、展示和编辑传感器数据，支持数据操作权限控制
  3. 有毒气体数据库管理 - 提供气体信息的CRUD操作，支持搜索、过滤和统计分析
  4. 案例文件管理系统 - 支持树状结构文件浏览，提供文件预览和下载功能
  5. 地图集成展示 - 嵌入交互式地图页面，支持传感器位置可视化
  6. 会话管理与安全中间件 - 实现用户会话状态管理，保护敏感路由访问

  技术栈：
  • 前端框架：NiceGUI（基于Vue.js/Quasar）
  • 后端框架：FastAPI + Uvicorn
  • 数据存储：SQLite + Pandas DataFrame
  • 权限管理：自定义RBAC实现
  • 数据可视化：Quasar组件库

  架构亮点：
  • 模块化设计 - 各功能模块解耦，便于维护和扩展
  • 中间件安全防护 - 通过认证中间件保护所有敏感路由
  • 响应式UI设计 - 支持不同屏幕尺寸和用户交互
  • 实时数据更新 - 传感器数据动态刷新和权限实时生效

  应用场景：
  适用于工业安全监控、环境监测、实验室数据管理、多用户协作平台等需要
  权限控制和数据可视化的专业领域。
