# user_service.py
from sqlalchemy.orm import Session
from sqlalchemy import or_
from typing import Optional, List
from .models import User, RoleEnum
from .auth_manager import PermissionManager
from . import logger


class UserService:
    """用户管理服务"""

    def __init__(self, session: Session):
        self.session = session
        self.permission_manager = PermissionManager(session)

    def create_user(self, username: str, password: str,
                    email: Optional[str] = None,
                    role: str = RoleEnum.GUEST.value, **kwargs) -> Optional[User]:
        """创建新用户"""
        try:
            if not email:
                email = f'{username}@autogenerated.com'
            # 检查用户名和邮箱是否已存在
            if self.session.query(User).filter(
                or_(User.username == username, User.email == email)
            ).first():
                logger.error(f"用户名或邮箱已存在: {username}, {email}")
                return None

            # 创建用户
            user = User(username=username, email=email, role=role, **kwargs)
            user.set_password(password)

            self.session.add(user)
            self.session.commit()

            # 分配角色对应的默认权限
            self.permission_manager.assign_role_permissions(user)

            logger.info(f"用户创建成功: {username}")
            return user

        except Exception as e:
            self.session.rollback()
            logger.error(f"创建用户失败: {e}")
            return None

    def authenticate_user(self, identifier: str, password: str) -> Optional[User]:
        """用户认证"""
        user = self.session.query(User).filter(
            or_(User.username == identifier, User.email == identifier)
        ).first()

        if user and user.check_password(password) and user.is_active:
            return user
        return None

    def update_user_role(self, user_id: int, new_role: str,
                         updater: User = None) -> bool:
        """更新用户角色"""
        try:
            user = self.session.query(User).get(user_id)
            if not user:
                return False

            # 检查权限（如果不是管理员操作）
            if updater and not updater.is_admin():
                logger.warning(f"非管理员尝试修改用户角色: {updater.username}")
                return False

            old_role = user.role
            user.role = new_role

            # 重新分配权限
            self.permission_manager.assign_role_permissions(user)

            self.session.commit()
            logger.info(f"用户角色更新: {user.username} {old_role} -> {new_role}")
            return True

        except Exception as e:
            self.session.rollback()
            logger.error(f"更新用户角色失败: {e}")
            return False

    def get_user_by_id(self, user_id: int) -> Optional[User]:
        """根据ID获取用户"""
        return self.session.query(User).get(user_id)

    def get_user_by_username(self, username: str) -> Optional[User]:
        """根据用户名获取用户"""
        return self.session.query(User).filter_by(username=username).first()

    def list_users(self, role: str = None, active_only: bool = True) -> List[User]:
        """列出用户"""
        query = self.session.query(User)

        if role:
            query = query.filter_by(role=role)

        if active_only:
            query = query.filter_by(is_active=True)

        return query.order_by(User.created_at.desc()).all()

    def deactivate_user(self, user_id: int, updater: User = None) -> bool:
        """停用用户"""
        try:
            user = self.session.query(User).get(user_id)
            if not user:
                return False

            # 检查权限
            if updater and not updater.is_admin():
                logger.warning(f"非管理员尝试停用用户: {updater.username}")
                return False

            user.is_active = False
            self.session.commit()
            logger.info(f"用户已停用: {user.username}")
            return True

        except Exception as e:
            self.session.rollback()
            logger.error(f"停用用户失败: {e}")
            return False

    def activate_user(self, user_id: int, updater: User = None) -> bool:
        """激活用户"""
        try:
            user = self.session.query(User).get(user_id)
            if not user:
                return False

            # 检查权限
            if updater and not updater.is_admin():
                logger.warning(f"非管理员尝试激活用户: {updater.username}")
                return False

            user.is_active = True
            self.session.commit()
            logger.info(f"用户已激活: {user.username}")
            return True

        except Exception as e:
            self.session.rollback()
            logger.error(f"激活用户失败: {e}")
            return False
